# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


GET http://passerby.cn/api/v1/login?code=test
Accept: application/json

###

GET http://passerby.cn/api/v1/users?access-token=5plYgmXGgsbxKLfVfn0STViBi9hynwfw
Accept: application/json

###

GET http://passerby.cn/api/v1/users/7?access-token=59a1af448c3cd7f250e0635c39a05a5a
Accept: application/json

###

POST http://passerby.cn/api/v1/users/wechat?access-token=5plYgmXGgsbxKLfVfn0STViBi9hynwfw
Content-Type: application/json

{
  "rawData": "test",
  "signature": "test",
  "encryptedData": "test",
  "iv": "test"
}

###

POST http://passerby.cn/api/v1/users?access-token=59a1af448c3cd7f250e0635c39a05a5a
Content-Type: application/json

{
  "username": "test2",
  "nickname": "小猪费奇2",
  "avatar": "uploads/3.png",
  "gender": 1,
  "birthday": 1992,
  "education": 0,
  "marriage": 1,
  "job": "工程师"
}

###

GET http://passerby.cn/api/v1/user-collects?access-token=testaf448c3cd7f250e0635c39a0test
Accept: application/json

###

POST http://passerby.cn/api/v1/user-collects?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "uid": 7,
  "remark": "测试"
}

###

PUT http://passerby.cn/api/v1/user-collects/6?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "remark": "测试2"
}

###

GET http://passerby.cn/api/v1/user-experiences?access-token=testaf448c3cd7f250e0635c39a0test
Accept: application/json

###

POST http://passerby.cn/api/v1/user-experiences?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "start_date": 20170101,
  "end_date": 20180101,
  "content": "这是一条很长长的工作经历"
}

###

PUT http://passerby.cn/api/v1/user-experiences/2?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "start_date": 20170101,
  "end_date": 20180101,
  "content": "这是一条很长长的工作经历"
}

###