# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


GET http://passerby.test/api/v1/login?code=test
Accept: application/json

###

GET http://passerby.test/api/v1/users?access-token=testaf448c3cd7f250e0635c39a0test&where[nickname][like]=小
Accept: application/json

###

GET http://passerby.test/api/v1/users/2?access-token=59a1af448c3cd7f250e0635c39a05a5a
Accept: application/json

###

POST http://passerby.test/api/v1/users/wechat?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "rawData": "test",
  "signature": "test",
  "encryptedData": "test",
  "iv": "test"
}

###

POST http://passerby.test/api/v1/users?access-token=59a1af448c3cd7f250e0635c39a05a5a
Content-Type: application/json

{
  "username": "test3",
  "nickname": "小猪费奇2",
  "avatar": "uploads/3.png",
  "gender": 1,
  "birthday": 19920120,
  "education": 0,
  "marriage": 1,
  "job": "工程师",
  "hobby": "打蓝球",
  "price": 1

}

###

GET http://passerby.test/api/v1/user-collects?access-token=testaf448c3cd7f250e0635c39a0test&page=1
Accept: application/json

###

POST http://passerby.test/api/v1/user-collects?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "uid": 11,
  "remark": "测试"
}

###

POST http://passerby.test/api/v1/user-collects/1?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "remark": "测试2"
}

###

POST http://passerby.test/api/v1/user-collects/delete/1?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
}

###

GET http://passerby.test/api/v1/user-experiences?access-token=testaf448c3cd7f250e0635c39a0test
Accept: application/json

###

GET http://passerby.test/api/v1/user-experiences/2?access-token=testaf448c3cd7f250e0635c39a0test
Accept: application/json

###

POST http://passerby.test/api/v1/user-experiences?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "content": "这是一条很长长的工作经历"
}

###

POST http://passerby.test/api/v1/user-experiences/2?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "content": "这是一条很长长的工作经历这是一条很长长的工作经历这是一条很长长的工作经历"
}

###

GET http://passerby.test/api/v1/helps?access-token=testaf448c3cd7f250e0635c39a0test
Accept: application/json

###

GET http://passerby.test/api/v1/helps/2?access-token=testaf448c3cd7f250e0635c39a0test
Accept: application/json

###

POST http://passerby.test/api/v1/helps?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "is_emergency": 1,
  "is_pay": 1,
  "end_date": 20190101,
  "content": "这是一条很长长的内容这是一条很长长的内容这是一条很长长的内容这是一条很长长的内容"
}

###

POST http://passerby.test/api/v1/helps/2?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "content": "这是一条很长长的工作经历这是一条很长长的工作经历这是一条很长长的工作经历"
}

###


GET http://passerby.test/api/v1/help-comments?access-token=testaf448c3cd7f250e0635c39a0test&where[help_id]=3
Accept: application/json

###

GET http://passerby.test/api/v1/help-comments/2?access-token=testaf448c3cd7f250e0635c39a0test
Accept: application/json

###

POST http://passerby.test/api/v1/help-comments?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "help_id": 3,
  "content": "这是一条很长长的内容这是一条很长长的内容这是一条很长长的内容这是一条很长长的内容"
}

###

POST http://passerby.test/api/v1/help-comments/2?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "content": "这是一条很长长的工作经历这是一条很长长的工作经历这是一条很长长的工作经历"
}

###

GET http://passerby.test/api/v1/user-stars?access-token=testaf448c3cd7f250e0635c39a0test&uid=2
Accept: application/json

###

POST http://passerby.test/api/v1/user-stars?access-token=testaf448c3cd7f250e0635c39a0test
Content-Type: application/json

{
  "uid": 2,
  "understand": 2,
  "help": 5,
  "reason": 5,
  "content": "这是一条很长长的工作经历这是一条很长长的工作经历这是一条很长长的工作经历"
}

###