<?php
/**
 * Author: lf
 * Blog: https://blog.feehi.com
 * Email: job@feehi.com
 * Created at: 2017-08-30 19:04
 */

namespace api\modules\v1\models;

use Yii;

class Charge extends \common\models\Charge
{

    public function fields()
    {
        $fields = parent::fields();
        unset($fields['updated_at']);

        $fields['created_at'] = function ($model){
            return date("Y-m-d", $model->created_at);
        };
//        $fields['nickname'] = function ($model) {
//            return $model->user->nickname;
//        };
//        $fields['avatar'] = function ($model) {
//           return Util::getFileRightUrl($model->user->avatar);
//        };
        return $fields;
    }

    public function beforeValidate()
    {
        if(!Yii::$app->getUser()->getIsGuest()){
            $this->uid = Yii::$app->getUser()->getIdentity()->getId();
        }
        return parent::beforeValidate();
    }

    public function transactions()
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_UPDATE,
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        //微信回调成功，给用户余额加钱
        if (!$insert && isset($changedAttributes['status']) && $this->status == self::STATUS_PAY_SUCCESS) {//微信支付回调成功后给用户加钱
            $model = User::findOne(['id' => $this->uid]);
            if ($model !== null) {
                $model->updateCounters(['balance' => $this->total_fee]);
            }
            //流水表添加记录
            Consume::addRow($this->uid, $this->total_fee, Consume::TYPE_CHARGE);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}