<?php
/**
 * Author: lf
 * Blog: https://blog.feehi.com
 * Email: job@feehi.com
 * Created at: 2017-08-30 19:04
 */

namespace api\modules\v1\models;

use Yii;

class Withdrawal extends \common\models\Withdrawal
{

    public function fields()
    {
        $fields = parent::fields();

        $fields['created_at'] = function ($model){
            return date("Y-m-d", $model->created_at);
        };
//        $fields['nickname'] = function ($model) {
//            return $model->user->nickname;
//        };
//        $fields['avatar'] = function ($model) {
//                return Util::getFileRightUrl($model->user->avatar);
//        };
        return $fields;
    }

    public function beforeValidate()
    {
        if(!Yii::$app->getUser()->getIsGuest()){
            $this->uid = Yii::$app->getUser()->getIdentity()->getId();
        }
        return parent::beforeValidate();
    }

    public function transactions()
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_INSERT,
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {//提现成功才添加一条提现记录，并减去用户账户的余额
            $model = User::findOne(['id' => $this->uid]);
            if ($model !== null) {
                $model->updateCounters(['balance' => $this->amount]);
            }

            //流水表添加记录
            Consume::addRow($this->uid, $this->amount, Consume::TYPE_WITHDRAWAL);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}